// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjCorlr3DUldW7VS3t6fTnHeTIA7x1NvY',
    appId: '1:262891480588:web:d768ea69327f75a8b5b029',
    messagingSenderId: '262891480588',
    projectId: 'tic-tac-toe-5e455',
    authDomain: 'tic-tac-toe-5e455.firebaseapp.com',
    storageBucket: 'tic-tac-toe-5e455.firebasestorage.app',
    measurementId: 'G-VF8N6TGB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPL68QfURyTISZ7d9Dcyc1lnAyZ0_CaXE',
    appId: '1:262891480588:android:849f3112496a69c3b5b029',
    messagingSenderId: '262891480588',
    projectId: 'tic-tac-toe-5e455',
    storageBucket: 'tic-tac-toe-5e455.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSuuIhN4_yehwsq5d_SPipwHBBlqQkKI',
    appId: '1:262891480588:ios:4c14047a6b11f720b5b029',
    messagingSenderId: '262891480588',
    projectId: 'tic-tac-toe-5e455',
    storageBucket: 'tic-tac-toe-5e455.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSuuIhN4_yehwsq5d_SPipwHBBlqQkKI',
    appId: '1:262891480588:ios:4c14047a6b11f720b5b029',
    messagingSenderId: '262891480588',
    projectId: 'tic-tac-toe-5e455',
    storageBucket: 'tic-tac-toe-5e455.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjCorlr3DUldW7VS3t6fTnHeTIA7x1NvY',
    appId: '1:262891480588:web:532e0febb9424a0bb5b029',
    messagingSenderId: '262891480588',
    projectId: 'tic-tac-toe-5e455',
    authDomain: 'tic-tac-toe-5e455.firebaseapp.com',
    storageBucket: 'tic-tac-toe-5e455.firebasestorage.app',
    measurementId: 'G-JFQVRFV32W',
  );
}
